# Generated by Django 4.1.1 on 2022-10-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://covesurfandturf.com/wp-content/uploads/2021/09/food-placeholder-1.jpg', max_length=500),
        ),
    ]
