# Generated by Django 4.1.1 on 2022-11-27 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_sample'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sample',
            new_name='Basic',
        ),
    ]
